package hello;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
@SpringBootApplication
public class App {
    private static final String HELLO_WORLD = "Hello world!";
    public String getGreeting() {
        return HELLO_WORLD;
    }

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}